name: Bisect

# Workflow runs when LilitHafner.com triggers it using the API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      trigger-link:
        description: 'Link to the comment that triggered this workflow'
        required: true
        type: string
      auth:
        description: 'Token to authorize posting a response to that link'
        required: true
        type: string

jobs:
  # This workflow contains a single job called "bisect"
  bisect:
    runs-on: ubuntu-latest
    
    # No permissions! This workflow executes arbitrary code
    # from untrusted sources and could easliy leak the token
    permissions: {}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Rate limit (before)
      run: >
        gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /rate_limit
      env:
        GH_TOKEN: ${{ github.token }}
    - uses: actions/checkout@v4
      with: 
        repository: LilithHafner/Bisect.jl
        ref: main
    - uses: julia-actions/setup-julia@v1
    - uses: julia-actions/cache@v1
    - uses: julia-actions/julia-buildpkg@v1  
    - name: Run bisetcion
      run: julia --project -e 'using Bisect; Bisect.workflow()'
      env:
        BISECT_TRIGGER_LINK: ${{ inputs.trigger-link }}
        GH_TOKEN: ${{ github.token }} # Need this to download the package
        BISECT_AUTH: ${{ inputs.auth }}
    - name: Rate limit (after)
      run: >
        gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /rate_limit
      env:
        GH_TOKEN: ${{ github.token }}
